### ISSUE TITLE
s42c missing from repo?

### ISSUE THREAD

**Issue by frollard** [bigtreetech/BIGTREETECH-Stepper-Motor-Driver#10]
Not sure if I'm looking in the wrong place - Website and sellers have s42c version of the closed loop driver, but no source available here.

**Comment by AndreyShpilevoy** [comment]
@frollard  https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/blob/master/BIGTREETECH%20S42C%20V1.0/readme.md

**Comment by frollard** [comment]
Thank you for pointing it out. Hurray for up to date things :)
